from ubuntu:18.04

run apt-get update
run apt-get install -y qemu-static libc6-dev-*-cross flex simh build-essential
# for c-sky
run apt-get install -y libmpfr-dev libmpc-dev
run apt-get build-dep -y qemu-static
